import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/toggle";
import {Sidebar} from "@/components/sidebar";

export const metadata: Metadata = {
  title: "crud-test-database",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html suppressHydrationWarning lang="es">
      <body className="container mx-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background p-5 font-sans">
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <header className="flex justify-between p-5 text-xl font-bold leading-[4rem]">
            <Link href="/">App para gestionar invitados</Link>
            <ModeToggle />
          </header>
          <main className="flex gap-5 overflow-auto py-8">
            <Sidebar />
            {children}
          </main>
          <footer className="text-center leading-[4rem] opacity-70">
            © {new Date().getFullYear()} crud-test-database
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
